Use vim to automatically reformat the coding style

diff --git a/diary b/diary
--- a/diary
+++ b/diary
@@ -35,17 +35,17 @@ DIARY_USE_GIT=1
 #  Save the current xterm label
 XTITLE=
 if [ "$TERM" == "xterm" ]; then
-   XPROPS=`xprop -id $WINDOWID 2>/dev/null`
-   if [ ! -z "$XPROPS" ]; then
-      XTITLE=`echo "$XPROPS" | grep WM_NAME | cut -d= -f2\
-                                     | sed -e 's/"\(.*\)"/\1/g'`
-   fi
+    XPROPS=`xprop -id $WINDOWID 2>/dev/null`
+    if [ ! -z "$XPROPS" ]; then
+        XTITLE=`echo "$XPROPS" | grep WM_NAME | cut -d= -f2\
+            | sed -e 's/"\(.*\)"/\1/g'`
+    fi
 fi
 
 #  Respect the EDITOR environment variable, if it exists
 if [ "$EDITOR" = "" ]; then
-   EDITOR="/usr/bin/vim"
-   EDIT_OPTIONS="-c :$ -c \"set textwidth=80 fen fdm=marker\""
+    EDITOR="/usr/bin/vim"
+    EDIT_OPTIONS="-c :$ -c \"set textwidth=80 fen fdm=marker\""
 fi
 
 # Less configuration variables
@@ -80,7 +80,7 @@ use_git() {
 # Set the label of the xterm instance
 #
 label_xterm() {
-   [ ! -z "$XTITLE" ] && echo -n "]0;$1"
+    [ ! -z "$XTITLE" ] && echo -n "]0;$1"
 }
 
 #
@@ -90,8 +90,8 @@ label_xterm() {
 #   1) Filepath
 #
 timestamp() {
-  # Strip possible floating part (it is present at least in GNU coreutils 8.6)
-  stat -c %Y "$1" | cut -f1 -d.
+    # Strip possible floating part (it is present at least in GNU coreutils 8.6)
+    stat -c %Y "$1" | cut -f1 -d.
 }
 
 #
@@ -109,14 +109,14 @@ timestamp() {
 #   echo abc hi there | filter_list ccc XX #->
 #
 filter_list() {
-   AWK_PROGRAM='
-      BEGIN { m=0; }
-      {
-         if (!m && $0 >= b) m=1;
-         if (m && e != "" && $0 > e) exit;
-         if (m) print;
-      }'
-   awk -vb="$1" -ve="$2" "$AWK_PROGRAM"
+    AWK_PROGRAM='
+    BEGIN { m=0; }
+    {
+        if (!m && $0 >= b) m=1;
+        if (m && e != "" && $0 > e) exit;
+        if (m) print;
+    }'
+    awk -vb="$1" -ve="$2" "$AWK_PROGRAM"
 }
 
 # ======================================================================
@@ -134,9 +134,9 @@ unified_date() {
 # if `strptime` utility is available, use it to recognize dates
 # specified in user's locale format
 user_date() {
-  unified_date "$1" 2>/dev/null ||
-  strptime '%x' '%Y/%m/%d/%H:%M:%S' <<< "$1" 2>/dev/null ||
-  ( echo "Invalid date \"$1\"" >&2; return 1 )
+    unified_date "$1" 2>/dev/null ||
+        strptime '%x' '%Y/%m/%d/%H:%M:%S' <<< "$1" 2>/dev/null ||
+        ( echo "Invalid date \"$1\"" >&2; return 1 )
 }
 
 #
@@ -183,7 +183,7 @@ header() {
 #   1) Name of the entry file
 #
 _entry_filepath() {
-   echo $PAGEDIR/$1.cal
+    echo $PAGEDIR/$1.cal
 }
 
 _entry_filepath_from_diarypath() {
@@ -197,21 +197,21 @@ _entry_filepath_from_diarypath() {
 #   1) File name for the entry to check
 #
 _entry_ensure_exists() {
-   FILEPATH=`_entry_filepath $1`
-   if [ -f $FILEPATH ]
-   then
-      echo 'existing'
-      return
-   fi
+    FILEPATH=`_entry_filepath $1`
+    if [ -f $FILEPATH ]
+    then
+        echo 'existing'
+        return
+    fi
 
-   DIR=`dirname $FILEPATH`
-   mkdir -p $DIR
+    DIR=`dirname $FILEPATH`
+    mkdir -p $DIR
 
-   echo "                         `header $1`" > $FILEPATH
-   echo >> $FILEPATH
+    echo "                         `header $1`" > $FILEPATH
+    echo >> $FILEPATH
 
-   echo 'new'
-   return
+    echo 'new'
+    return
 }
 
 #
@@ -227,14 +227,14 @@ _entry_ensure_exists() {
 #   *) Additional arguments to the callback function
 #
 _entry_change() {
-   FILE=$1
-   CALLBACK=$2
-   shift 2
+    FILE=$1
+    CALLBACK=$2
+    shift 2
 
-   STATUS=$(_entry_ensure_exists $FILE)
+    STATUS=$(_entry_ensure_exists $FILE)
 
-   FILEPATH=`_entry_filepath $FILE`
-   eval $CALLBACK $FILE $FILEPATH $STATUS $(printf '%q' "$*")
+    FILEPATH=`_entry_filepath $FILE`
+    eval $CALLBACK $FILE $FILEPATH $STATUS $(printf '%q' "$*")
 }
 
 # Viewing actions
@@ -247,9 +247,9 @@ _entry_change() {
 #   1) The file name of the entry
 #
 entry_cat() {
-   FILEPATH=`_entry_filepath $1`
-   [ -f $FILEPATH ] && cat $FILEPATH
-   return $?
+    FILEPATH=`_entry_filepath $1`
+    [ -f $FILEPATH ] && cat $FILEPATH
+    return $?
 }
 
 #
@@ -259,15 +259,15 @@ entry_cat() {
 #   1) The file name of the entry
 #
 entry_view() {
-   FILEPATH=`_entry_filepath $1`
-   if [ -f $FILEPATH ]
-   then
-      label_xterm "Diary: view $1"
-      less -c +g $FILEPATH
-      label_xterm $XTITLE
-      return 0
-   fi
-   return 1
+    FILEPATH=`_entry_filepath $1`
+    if [ -f $FILEPATH ]
+    then
+        label_xterm "Diary: view $1"
+        less -c +g $FILEPATH
+        label_xterm $XTITLE
+        return 0
+    fi
+    return 1
 }
 
 # The "edit" action
@@ -286,28 +286,28 @@ entry_view() {
 #   3) Status of the file
 #
 _entry_edit() {
-   FILE=$1
-   FILEPATH=$2
-   STATUS=$3
+    FILE=$1
+    FILEPATH=$2
+    STATUS=$3
 
-   OLD_TIMESTAMP=$(timestamp $FILEPATH)
-   label_xterm "Diary: edit $FILE"
-   $EDITOR $EDIT_OPTIONS $FILEPATH
-   label_xterm $XTITLE
-   NEW_TIMESTAMP=$(timestamp $FILEPATH)
+    OLD_TIMESTAMP=$(timestamp $FILEPATH)
+    label_xterm "Diary: edit $FILE"
+    $EDITOR $EDIT_OPTIONS $FILEPATH
+    label_xterm $XTITLE
+    NEW_TIMESTAMP=$(timestamp $FILEPATH)
 
-   if [ $STATUS = 'new' -a $NEW_TIMESTAMP -eq $OLD_TIMESTAMP ]
-   then
-      rm -f $FILEPATH
+    if [ $STATUS = 'new' -a $NEW_TIMESTAMP -eq $OLD_TIMESTAMP ]
+    then
+        rm -f $FILEPATH
 
-      # remove empty directories
-      while true
-      do
-        FILEPATH=$(dirname $FILEPATH)
-        [ $FILEPATH == $PAGEDIR ] && break
-        rmdir $FILEPATH &>/dev/null || break
-      done
-  else
+        # remove empty directories
+        while true
+        do
+            FILEPATH=$(dirname $FILEPATH)
+            [ $FILEPATH == $PAGEDIR ] && break
+            rmdir $FILEPATH &>/dev/null || break
+        done
+    else
         builtin cd $DIARYDIR
         FILEPATH=$(_entry_filepath_from_diarypath $FILE)
 
@@ -321,7 +321,7 @@ _entry_edit() {
         else
             use_git && stderr "Could not commit, no git directory there"
         fi
-   fi
+    fi
 }
 
 #
@@ -333,7 +333,7 @@ _entry_edit() {
 #   1) File to change
 #
 entry_edit() {
-   _entry_change $1 _entry_edit
+    _entry_change $1 _entry_edit
 }
 
 # The "entry" action
@@ -350,10 +350,10 @@ entry_edit() {
 #   1) Filepath to write to
 #
 _entry_add_entry() {
-   FILE=$2
-   shift 3
+    FILE=$2
+    shift 3
 
-   echo `date +%H:%M` $@ >> $FILE
+    echo `date +%H:%M` $@ >> $FILE
 }
 
 #
@@ -365,10 +365,10 @@ _entry_add_entry() {
 #   about to be created
 #
 entry_add_entry() {
-   FILE=$1
-   shift
+    FILE=$1
+    shift
 
-   _entry_change $FILE _entry_add_entry $@
+    _entry_change $FILE _entry_add_entry $@
 }
 
 # ======================================================================
@@ -389,41 +389,41 @@ entry_add_entry() {
 #   3) Interval specification
 #
 _diary_handle_interval() {
-   CALLBACK_FOR_SINGLE_DATE=$1
-   CALLBACK_FOR_INTERVAL=$2
-   shift 2
+    CALLBACK_FOR_SINGLE_DATE=$1
+    CALLBACK_FOR_INTERVAL=$2
+    shift 2
 
-   # Split arguments on "-"
-   FIRST="1"
-   FIRST_DATE=""
-   SECOND_DATE=""
-   for arg; do
-      if [ "$arg" == "-" -a -n "$FIRST" ]; then
-         FIRST=""
-         continue
-      fi
-      [ -n "$FIRST" ] && FIRST_DATE="$FIRST_DATE $arg" || SECOND_DATE="$SECOND_DATE $arg"
-   done
+    # Split arguments on "-"
+    FIRST="1"
+    FIRST_DATE=""
+    SECOND_DATE=""
+    for arg; do
+        if [ "$arg" == "-" -a -n "$FIRST" ]; then
+            FIRST=""
+            continue
+        fi
+        [ -n "$FIRST" ] && FIRST_DATE="$FIRST_DATE $arg" || SECOND_DATE="$SECOND_DATE $arg"
+    done
 
-   # If there is no "-", run the callback for single date and return
-   FIRST_DATE=`user_date "$FIRST_DATE"` || return 1
-   SECOND_DATE=`user_date "$SECOND_DATE"` || return 1
-   if [ -n "$FIRST" ]; then
-       eval $CALLBACK_FOR_SINGLE_DATE $(latest_file_for "$FIRST_DATE")
-      return $?
-   fi
+    # If there is no "-", run the callback for single date and return
+    FIRST_DATE=`user_date "$FIRST_DATE"` || return 1
+    SECOND_DATE=`user_date "$SECOND_DATE"` || return 1
+    if [ -n "$FIRST" ]; then
+        eval $CALLBACK_FOR_SINGLE_DATE $(latest_file_for "$FIRST_DATE")
+        return $?
+    fi
 
-   # Search for diary entries for dates withing the specified interval.
-   # If there are any entries, run the second callback passing found file names
-   builtin cd $PAGEDIR
-   FILES="`
-      find . -name '??.cal' | sort |
-      sed -e 's:^\./::; s:\.cal$::' |
-      filter_list $FIRST_DATE $SECOND_DATE |
-      sed -e 's:$:.cal:'`"
-   if [ -n "$FILES" ]; then
-      eval $CALLBACK_FOR_INTERVAL $FIRST_DATE $SECOND_DATE $FILES
-   fi
+    # Search for diary entries for dates withing the specified interval.
+    # If there are any entries, run the second callback passing found file names
+    builtin cd $PAGEDIR
+    FILES="`
+    find . -name '??.cal' | sort |
+    sed -e 's:^\./::; s:\.cal$::' |
+    filter_list $FIRST_DATE $SECOND_DATE |
+    sed -e 's:$:.cal:'`"
+    if [ -n "$FILES" ]; then
+        eval $CALLBACK_FOR_INTERVAL $FIRST_DATE $SECOND_DATE $FILES
+    fi
 }
 
 # The "cat" action
@@ -438,11 +438,11 @@ _diary_handle_interval() {
 #   *) File path to print
 #
 _diary_cat_interval() {
-   shift 2
-   for file; do
-      cat "$file"
-      echo
-   done
+    shift 2
+    for file; do
+        cat "$file"
+        echo
+    done
 }
 
 #
@@ -452,7 +452,7 @@ _diary_cat_interval() {
 #   *) Interval specification
 #
 diary_cat() {
-   _diary_handle_interval entry_cat _diary_cat_interval "$@"
+    _diary_handle_interval entry_cat _diary_cat_interval "$@"
 }
 
 # The "view" action
@@ -467,13 +467,13 @@ diary_cat() {
 #   *) File pathes
 #
 _diary_view_interval() {
-   FIRST_DATE=$1
-   SECOND_DATE=$2
-   shift 2
+    FIRST_DATE=$1
+    SECOND_DATE=$2
+    shift 2
 
-   label_xterm "Diary: view $FIRST_DATE - $SECOND_DATE"
-   less "$@"
-   label_xterm $XTITLE
+    label_xterm "Diary: view $FIRST_DATE - $SECOND_DATE"
+    less "$@"
+    label_xterm $XTITLE
 }
 
 #
@@ -486,7 +486,7 @@ _diary_view_interval() {
 #   *) interval specification
 #
 diary_view() {
-   _diary_handle_interval entry_view _diary_view_interval "$@"
+    _diary_handle_interval entry_view _diary_view_interval "$@"
 }
 
 # Editing actions
@@ -499,7 +499,7 @@ diary_view() {
 #   *) user_date() arguments
 #
 diary_edit() {
-   DATE=`user_date "$*"` && entry_edit $DATE || return 1
+    DATE=`user_date "$*"` && entry_edit $DATE || return 1
 }
 
 #
@@ -509,7 +509,7 @@ diary_edit() {
 #   *) Arguments for entry_add_entry()
 #
 diary_add_entry() {
-   entry_add_entry $(unified_date) $@ || return 1
+    entry_add_entry $(unified_date) $@ || return 1
 }
 
 # Searching
@@ -522,8 +522,8 @@ diary_add_entry() {
 #   *) grep arguments
 #
 diary_grep() {
-   builtin cd $PAGEDIR
-   grep "$@" `find . -name '??:??:??.cal' | sed 's:^\./::' | sort`
+    builtin cd $PAGEDIR
+    grep "$@" `find . -name '??:??:??.cal' | sed 's:^\./::' | sort`
 }
 
 #
@@ -535,22 +535,22 @@ diary_grep() {
 # Arguments: Not figured out yet
 #
 diary_search() {
-   if [ ! -f $LESSOPTS_FILE ] || [ $LESSOPTS_FILE -ot $0 ]; then
-      {
-         echo #command
-         echo $LESS_BACKKEY    next-file
-         echo $LESS_FWDKEY   prev-file
-      } > $LESSKEY_FILE
-      lesskey -o $LESSOPTS_FILE $LESSKEY_FILE
-      rm $LESSKEY_FILE
-   fi
+    if [ ! -f $LESSOPTS_FILE ] || [ $LESSOPTS_FILE -ot $0 ]; then
+        {
+            echo #command
+            echo $LESS_BACKKEY    next-file
+            echo $LESS_FWDKEY   prev-file
+        } > $LESSKEY_FILE
+        lesskey -o $LESSOPTS_FILE $LESSKEY_FILE
+        rm $LESSKEY_FILE
+    fi
 
-   builtin cd $PAGEDIR
-   label_xterm "Diary: search for $*"
-   egrep --files-with-matches "$*" `find . -name '??:??:??.cal' | sort -r` |
-      xargs less -P'"u" for older, "i" for newer' -k$LESSOPTS_FILE +"/$*
-" ++g
-   label_xterm $XTITLE
+    builtin cd $PAGEDIR
+    label_xterm "Diary: search for $*"
+    egrep --files-with-matches "$*" `find . -name '??:??:??.cal' | sort -r` |
+    xargs less -P'"u" for older, "i" for newer' -k$LESSOPTS_FILE +"/$*
+    " ++g
+    label_xterm $XTITLE
 }
 
 diary_history() {
@@ -564,22 +564,22 @@ diary_history() {
 # ======================================================================
 
 get_old_pages() {
-   find $PAGEDIR -maxdepth 1 -name '????.??.??'
+    find $PAGEDIR -maxdepth 1 -name '????.??.??'
 }
 
 refile_old_pages() {
-   echo -n "Reorganizing page structure ... "
+    echo -n "Reorganizing page structure ... "
 
-   for fil in `get_old_pages`; do
-      FPATH=`echo $fil |
-             sed -e 's:\([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\):\1\/\2\/\3:'`
-      FPATH=$FPATH.cal
-      MONTHDIR=`dirname $FPATH`
+    for fil in `get_old_pages`; do
+        FPATH=`echo $fil |
+        sed -e 's:\([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\):\1\/\2\/\3:'`
+        FPATH=$FPATH.cal
+        MONTHDIR=`dirname $FPATH`
 
-      mkdir -p $MONTHDIR
-      mv $fil $FPATH
-      echo -n .
-   done
+        mkdir -p $MONTHDIR
+        mv $fil $FPATH
+        echo -n .
+    done
 }
 
 # ======================================================================
@@ -587,26 +587,22 @@ refile_old_pages() {
 # ======================================================================
 
 usage() {
-   cat << 'ENDUSAGE'
-Examples:
+    cat << 'ENDUSAGE'
+    Examples:
 
-  diary                       - open today's page for editing
-  diary edit yesterday        - this is cheating! ... but you can edit
-                                past entries if you really want to
+    diary                       - open today's page for editing
+    diary edit yesterday        - this is cheating! ... but you can edit past entries if you really want to
 
-  diary entry Hi World        - add a line to today's diary page
+    diary entry Hi World        - add a line to today's diary page
 
-  diary cat                   - dump today's page to stdout
-  diary cat last Monday       - dump last Monday's page to stdout
-  diary cat last Mon - today  - dump entries from last Monday till today
-  diary view <...>            - equivalent to `diary cat`, but opens
-                                matching entries for viewing
+    diary cat                   - dump today's page to stdout
+    diary cat last Monday       - dump last Monday's page to stdout
+    diary cat last Mon - today  - dump entries from last Monday till today
+    diary view <...>            - equivalent to `diary cat`, but opens matching entries for viewing
 
-  diary grep [Ff]ind          - grep pages for lines containing find or Find
-  diary grep -F Find          - search for fixed string (options are passed
-                                directly to grep)
-  diary search "^Fixed"       - open pages for viewing that contain
-                                lines that start with "Fixed"
+    diary grep [Ff]ind          - grep pages for lines containing find or Find
+    diary grep -F Find          - search for fixed string (options are passed directly to grep)
+    diary search "^Fixed"       - open pages for viewing that contain lines that start with "Fixed"
 ENDUSAGE
 }
 
@@ -621,63 +617,63 @@ mkdir -p $PAGEDIR
 [ -n "`get_old_pages`" ] && refile_old_pages
 
 if [ $# = 0 ]; then
-   diary_edit
+    diary_edit
 elif [ $# = 1 ]; then
-   PARAM=`echo $1 | tr A-Z a-z`
-   case $PARAM in
-      help | ? | usage | -h | --help )
-         usage
-      ;;
-      cat )
-         diary_cat
-      ;;
-      view )
-         diary_view
-      ;;
-      edit )
-         diary_edit
-      ;;
-      grep | search )
-         echo "You need to specify search terms."
-      ;;
-      history )
-          diary_history
-      ;;
-      * )
-         echo "Invalid parameter: $@" >&2
-         exit 1
-      ;;
-   esac
+    PARAM=`echo $1 | tr A-Z a-z`
+    case $PARAM in
+        help | ? | usage | -h | --help )
+            usage
+            ;;
+        cat )
+            diary_cat
+            ;;
+        view )
+            diary_view
+            ;;
+        edit )
+            diary_edit
+            ;;
+        grep | search )
+            echo "You need to specify search terms."
+            ;;
+        history )
+            diary_history
+            ;;
+        * )
+            echo "Invalid parameter: $@" >&2
+            exit 1
+            ;;
+    esac
 else
-   PARAM=`echo $1 | tr A-Z a-z`
-   case $PARAM in
-      entry )
-         shift
-         diary_add_entry $@
-      ;;
-      cat )
-         shift
-         diary_cat $@
-      ;;
-      view )
-         shift
-         diary_view $@
-      ;;
-      edit )
-         shift
-         diary_edit $@
-      ;;
-      grep )
-         shift
-         diary_grep "$@"
-      ;;
-      search )
-         shift
-         diary_search $@
-      ;;
-      * )
-         echo "Invalid parameter: $@" >&2
-         exit 1
-      ;;
-   esac
+    PARAM=`echo $1 | tr A-Z a-z`
+    case $PARAM in
+        entry )
+            shift
+            diary_add_entry $@
+            ;;
+        cat )
+            shift
+            diary_cat $@
+            ;;
+        view )
+            shift
+            diary_view $@
+            ;;
+        edit )
+            shift
+            diary_edit $@
+            ;;
+        grep )
+            shift
+            diary_grep "$@"
+            ;;
+        search )
+            shift
+            diary_search $@
+            ;;
+        * )
+            echo "Invalid parameter: $@" >&2
+            exit 1
+            ;;
+    esac
 fi
